---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-gin
  template:
    metadata:
      labels:
        app: hello-gin
    spec:
      securityContext:
        fsgroup: 2000
        runAsUser: 1000
        fsGroup: 1000
      enableServiceLinks: false
      imagePullSecrets:
        - name: imgcred
      containers:
        - name: hello-gin
          image: harbor.codemowers.eu/kpets/hello-gin:latest
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: USERNAME
              value: world
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8080
              name: metrics
